service: goggins-api
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  timeout: 10

functions:
  api:
    handler: index.handler
    environment: ${file(env.json)}
    events:
      - httpApi: "*"
